package KieRule;
import lv.alija.zooRulesEngine.model.Visitor;

rule "Senior"

when
visitorObject : Visitor(type == "Senior" && age > 64 && haveCertificate==true);
then
visitorObject.setTicketPrice(2.50);
end;

rule "Student"

when
visitorObject : Visitor(type == "Student" && age < 64 && haveCertificate==true);
then
visitorObject.setTicketPrice(4.50);
end;

rule "Scholar"

when
visitorObject : Visitor(type == "Scholar" && age < 20 && haveCertificate==true);
then
visitorObject.setTicketPrice(3.50);
end;

rule "Kid"
when
visitorObject : Visitor(type == "Kid" && age < 7);
then
visitorObject.setTicketPrice(0.00);
end;

rule "Person"
when
visitorObject : Visitor(type == "Person");
then
visitorObject.setTicketPrice(10.00);
end;



